# Generated by Django 5.0 on 2023-12-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEOPLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('AGE', models.CharField(max_length=100)),
                ('CITY', models.CharField(max_length=100)),
            ],
        ),
    ]
