# Generated by Django 5.0 on 2023-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryModel', '0002_rename_age_people_age_rename_city_people_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
